### ISSUE TITLE
import_tileset bigbed seen as bigwig

### ISSUE THREAD

**Issue by astrovsky01** [higlass/higlass-server#133]
Trying to upload a bigbed file like in https://github.com/higlass/higlass-server/blob/develop/tilesets/tests.py#L333
```
/home/higlass/projects# python higlass-server/manage.py ingest_tileset --filetype chromsizes-tsv --datatype chromsizes --coordSystem hg38 --filename negspy/negspy/data/hg38/chromInfo.txt

(base) root@0e1e1724e5d2:/home/higlass/projects# python higlass-server/manage.py ingest_tileset --filename data/1.bigbed.bigbed --filetype bigbed --datatype gene-bed12-annotation --coordSystem hg38
```
returns
```
CommandError: No chromsizes available which match the chromosomes in this bigwig. See http://docs.higlass.io/data_preparation.html#bigwig-files for more information
```
Is this just an issue with the file, or is there some reason it's talking about a bigwig?
Thanks!

**Comment by pkerpedjiev** [comment]
It's a typo. The function used to only be called for bigWig files and when we added support for bigBed, we didn't change the warning.

Here's where the check function is called: https://github.com/higlass/higlass-server/blob/a2c70031a9bfaae55019e6b807ca0fde956674b2/tilesets/management/commands/ingest_tileset.py#L90

And here's where it prints the warning within that function:

https://github.com/higlass/higlass-server/blob/a2c70031a9bfaae55019e6b807ca0fde956674b2/tilesets/management/commands/ingest_tileset.py#L176

If you want to submit a PR to change the wording, I'll be happy to merge it. Otherwise I can do it in the next few days.

**Comment by astrovsky01** [comment]
I had figured, and was able to get around the error, thanks. Now the file is ingested and listed in the container among the available tilesets, just not showing up as an available track in the select.

**Comment by pkerpedjiev** [comment]
Oh, that's because we don't support `gene-bed12-annotation` as an available track type on the front end. @alexpreynolds may have gotten loading those to work so maybe he can chime in?

For gene annotation tracks you could try the approach that we use here: http://docs.higlass.io/data_preparation.html#gene-annotation-tracks

Or if you're lucky, it may just work by using `--filetype bigbed --datatype gene-annotations`. I've never tried this with bigbed files though.

**Comment by astrovsky01** [comment]
That makes sense. I am unfortunately not so lucky, but I have the ability to request the user provide a file for the track, so I think I can put it on them, then automate the track building. I really appreciate the help!

**Comment by alexpreynolds** [comment]
I have a fork of `higlass` that supports rendering bigBed as BED12:

https://github.com/alexpreynolds/higlass/tree/bed12

The track type is called `horizontal-gene-bed12-annotations` — a slight difference from what is used for `beddb` annotation tracks.

This is a little behind the current version of `higlass`, but not too far, I hope.

A custom version of `clodius` is needed to support querying bigBed files, with a local and custom installation of `higlass-server`. 

It uses the same library as is used for bigWig querying, but as these are annotations and not continuous signal, there are some bigBed-specific changes that are similar to how `beddb` returns a prioritized subset of annotations:

https://github.com/alexpreynolds/clodius/tree/bigbed-support

This is built off an older version of `clodius` and some work may be needed to bring in current commits from the upstream ("real") version of this tool. I have not had time to bring things in line.

This also requires some changes to `higlass-server`:

https://github.com/alexpreynolds/higlass-server/tree/bigbed-support

I don't have tests written for this, and there may be bugs I don't know about. Mainly I have thrown it against our bigBed file of interest (a set of DHSs) and things seem to work. 

Support for mocking was added by the HiGlass team in the last couple months, but I haven't had time to write the mock tests needed to query a test bigBed file I have on a public S3 bucket.

While performance has been okay for our use case, whole-genome queries of bigBed files return everything. For a dense bigBed file, this may reduce query speed. In any case, `clodius` takes a subset of this data for purposes of tile generation, once there are more than some threshold of elements (500, I think). 

I think Pete made some recent improvements (I haven't yet been able to test locally) to `beddb` querying and indexing, which might make BED queries even faster than bigBed querying, paradoxically. Pete could probably comment on this more specifically. 

Not trying to dissuade you from using bigBed, but because those `beddb` changes are also in the official release of `higlass` and other pieces of the ecosystem, it might be easier and faster to explore serving up BED data, instead of bigBed. 

Still, I hope my patches might offer some direction to go in if bigBed support is needed, until I can get them into the official distribution.

**Comment by astrovsky01** [comment]
@alexpreynolds I had been trying to allow upload of all listed datatypes, but they can be modified behind the scenes based on their datatypes. For now, I can just convert them to bed data from an uploaded bigbed, and it seems to work fine. I appreciate the clarification, and thanks for the help.
